services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=authdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

